version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  projetofiap.api:
    image: ${DOCKER_REGISTRY-}projetofiapapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  projetofiap.worker:
    image: ${DOCKER_REGISTRY-}projetofiapworker
    build:
      context: .
      dockerfile: ProjetoFiap.Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
